In [ ]:
import nltk
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('omw-1.4')

import torch



[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...


In [ ]:
from nltk.tokenize import word_tokenize #q1
from collections import Counter
import string

text = """Natural Language Processing is a field of Artificial Intelligence
that focuses on making computers understand human language."""

tokens = word_tokenize(text.lower())

# Remove punctuation
tokens = [w for w in tokens if w not in string.punctuation]

freq_dist = Counter(tokens)

print("Word Frequency Distribution:\n")
for word, freq in freq_dist.items():
    print(word, ":", freq)



Word Frequency Distribution:

natural : 1
language : 2
processing : 1
is : 1
a : 1
field : 1
of : 1
artificial : 1
intelligence : 1
that : 1
focuses : 1
on : 1
making : 1
computers : 1
understand : 1
human : 1


In [ ]:
from nltk.corpus import wordnet #2

word = "good"

synonyms = set()
antonyms = set()

for syn in wordnet.synsets(word):
    for lemma in syn.lemmas():
        synonyms.add(lemma.name())
        if lemma.antonyms():
            antonyms.add(lemma.antonyms()[0].name())

print("Word:", word)
print("Synonyms:", synonyms)
print("Antonyms:", antonyms)


Word: good
Synonyms: {'salutary', 'respectable', 'full', 'honorable', 'proficient', 'in_effect', 'effective', 'undecomposed', 'adept', 'soundly', 'safe', 'beneficial', 'commodity', 'upright', 'estimable', 'skilful', 'sound', 'ripe', 'well', 'near', 'practiced', 'unspoiled', 'good', 'unspoilt', 'trade_good', 'just', 'right', 'expert', 'dependable', 'skillful', 'honest', 'thoroughly', 'in_force', 'dear', 'goodness', 'serious', 'secure'}
Antonyms: {'evil', 'ill', 'bad', 'evilness', 'badness'}


In [ ]:
import torch #3

# Create random tensor of size (5,3)
tensor = torch.rand(5, 3)
print("Tensor:\n", tensor)

# Print shape
print("\nShape of tensor:", tensor.shape)

# Mathematical operation (addition)
tensor_add = tensor + 2
print("\nTensor after addition:\n", tensor_add)

# Sum of all elements
total_sum = torch.sum(tensor)
print("\nSum of all elements:", total_sum.item())


Tensor:
 tensor([[0.1760, 0.3362, 0.4485],
        [0.0722, 0.0252, 0.5612],
        [0.7085, 0.0489, 0.9842],
        [0.9646, 0.7597, 0.4306],
        [0.2273, 0.7826, 0.0059]])

Shape of tensor: torch.Size([5, 3])

Tensor after addition:
 tensor([[2.1760, 2.3362, 2.4485],
        [2.0722, 2.0252, 2.5612],
        [2.7085, 2.0489, 2.9842],
        [2.9646, 2.7597, 2.4306],
        [2.2273, 2.7826, 2.0059]])

Sum of all elements: 6.531671524047852


In [ ]:
import torch

# Create 1D tensor from 10 to 19
t1 = torch.arange(10, 20)
print("1D Tensor:", t1)

# First, last, middle elements
print("First element:", t1[0])
print("Last element:", t1[-1])
print("Middle elements:", t1[4:6])

# Create 2D tensor (3x4)
t2 = torch.arange(1, 13).reshape(3, 4)
print("\n2D Tensor:\n", t2)

# Extract first row
print("\nFirst Row:", t2[0])

# Extract last column
print("Last Column:", t2[:, -1])

# Extract 2x2 submatrix
print("2x2 Submatrix:\n", t2[0:2, 0:2])


1D Tensor: tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
First element: tensor(10)
Last element: tensor(19)
Middle elements: tensor([14, 15])

2D Tensor:
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

First Row: tensor([1, 2, 3, 4])
Last Column: tensor([ 4,  8, 12])
2x2 Submatrix:
 tensor([[1, 2],
        [5, 6]])
