In [ ]:
import torch
import numpy as np

tensor_from_list = torch.tensor([1, 2, 3])
print(tensor_from_list)

np_array = np.array([[1, 2], [3, 4]])
tensor_from_numpy = torch.from_numpy(np_array)
print(tensor_from_numpy)

tensor([1, 2, 3])
tensor([[1, 2],
        [3, 4]])


In [ ]:
import torch

a = torch.tensor([1, 2, 3])
b = torch.tensor([1, 2, 3])

addition = a + b
print(addition)

multiplication = a * b
print(multiplication)

tensor([2, 4, 6])
tensor([1, 4, 9])


In [ ]:
import torch
import numpy as np

t = torch.tensor([1, 2, 3])
print(t.shape)
print(t.dtype)

A = torch.tensor([[1, 2],
                  [3, 4]])
B = torch.tensor([[5, 6],
                  [7, 8]])
print(torch.mm(A, B))

x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])
print(torch.dot(x, y))

T = torch.tensor([[10, 20, 30],
                  [40, 50, 60]])
print(T[0])
print(T[1])
print(T[0][1])
print(T[1][2])

print(torch.empty(2, 3))
print(torch.zeros(2, 3))
print(torch.rand(2, 3))
print(torch.ones(2, 3))
print(torch.eye(3))
print(torch.arange(0, 10, 2))
print(torch.linspace(0, 1, 5))
print(torch.add(torch.tensor([1, 2, 3]), torch.tensor([4, 5, 6])))
print(torch.mm(torch.tensor([[1, 2]]), torch.tensor([[3], [4]])))
print(torch.dot(torch.tensor([1, 2]), torch.tensor([3, 4])))
print(torch.bmm(torch.rand(2, 3, 4), torch.rand(2, 4, 5)))
print(torch.abs(torch.tensor([-1, -2, 3])))
print(torch.argmax(torch.tensor([10, 20, 5])))
print(torch.argmin(torch.tensor([10, 20, 5])))
print(torch.mean(torch.tensor([1.0, 2.0, 3.0])))
print(torch.sort(torch.tensor([3, 1, 2])))
print(torch.cat((torch.tensor([1, 2]), torch.tensor([3, 4]))))


torch.Size([3])
torch.int64
tensor([[19, 22],
        [43, 50]])
tensor(32)
tensor([10, 20, 30])
tensor([40, 50, 60])
tensor(20)
tensor(60)
tensor([[1.4684e+33, 4.4900e-41, 1.4684e+33],
        [4.4900e-41, 8.4078e-45, 7.0065e-45]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.0268, 0.6547, 0.4089],
        [0.9856, 0.7977, 0.2143]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([0, 2, 4, 6, 8])
tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])
tensor([5, 7, 9])
tensor([[11]])
tensor(11)
tensor([[[1.1353, 1.0025, 1.3868, 0.8557, 1.9836],
         [0.5247, 0.6775, 0.8907, 0.3893, 1.0220],
         [0.8756, 0.9877, 0.9409, 0.6234, 0.9859]],

        [[1.7639, 2.2512, 1.9983, 1.2451, 1.4993],
         [1.7904, 1.7510, 1.6904, 1.2288, 1.4046],
         [1.0437, 0.9555, 0.8870, 0.7947, 0.9401]]])
tensor([1, 2, 3])
tensor(1)
tensor(2)
tensor(2.)
torch.return_types.sort(
values=tensor([1, 2, 3]),
indices=tensor